logging:
  path: /user/log/lamperouge/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lamperouge?useSSL=true&useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
