logging:
  path: ./log/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lamperouge?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
